name: PullRequest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - trunk-merge/**

jobs:
  pr:
    name: Run Pull Request checks
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        run: sleep 2s

      - name: Check run forever file existence
        id: run_forever
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: test/run_forever*.txt

      - name: Check branch name
        run: echo $BRANCH_NAME

      - name: Run forever
        if: steps.run_forever.outputs.diff && contains('trunk-merge', env.BRANCH_NAME)
        run: sleep 180s
